baseURL = 'https://amirany.ir/'
languageCode = 'en-us'
title = 'Yasin Amirany | Back-end Developer | Personal blog'

[taxonomies]
  category = "categories"
  tag = "tags"

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
  
[build]
  writeStats = true
